config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/pages/*id' => 'pages#show', as: :page, format: false

  root 'main#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  get 'main/senales', :as => 'senales_main'
  get 'main/educacion', :as => 'educacion_main'
  get 'main/plans', :as => 'plans_main'
  get 'main/premium', :as => 'premium_main'
  get 'main/welcome', :as => 'welcome_main'
  get 'main/ayuda', :as => 'ayuda_main'

  get 'dashboard/index', :as => 'dashboard_index'
  get 'dashboard/educacion', :as => 'dashboard_educacion'
  get 'dashboard/senales', :as => 'dashboard_senales'
  get 'dashboard/info', :as => 'dashboard_info'

  #Articles
  get 'academy/articulo', :as => 'academy_articulo'
  get 'academy/analisisTecnico', :as => 'academy_analisisTecnico'
  get 'academy/analisisTecnicoL1', :as => 'academy_analisisTecnicoL1'
  get 'academy/analisisTecnicoL2', :as => 'academy_analisisTecnicoL2'
  get 'academy/analisisTecnicoL3', :as => 'academy_analisisTecnicoL3'
  get 'academy/analisisTecnicoL4', :as => 'academy_analisisTecnicoL4'
  get 'academy/analisisTecnicoL5', :as => 'academy_analisisTecnicoL5'
  get 'academy/analisisTecnicoL6', :as => 'academy_analisisTecnicoL6'
  get 'academy/bancosCentrales', :as => 'academy_bancosCentrales'
  get 'academy/acciones', :as => 'academy_acciones'
  get 'academy/bitcoin', :as => 'academy_bitcoin'
  get 'academy/materias', :as => 'academy_materias'
  get 'academy/correlacion', :as => 'academy_correlacion'
  get 'academy/sentimiento', :as => 'academy_sentimiento'

  #Archive
  get 'archive/amxl', :as => 'archive_amxl'
  get 'archive/femsaubd', :as => 'archive_femsaubd'
  get 'archive/gfnorteo', :as => 'archive_gfnorteo'
  get 'archive/walmex', :as => 'archive_walmex'
  get 'archive/gmexicob', :as => 'archive_gmexicob'
  get 'archive/cemexcpo', :as => 'archive_cemexcpo'
  get 'archive/tlevisacpo', :as => 'archive_tlevisacpo'
  get 'archive/alfaa', :as => 'archive_alfaa'
  get 'archive/gapb', :as => 'archive_gapb'
  get 'archive/asurb', :as => 'archive_asurb'
  get 'archive/kofl', :as => 'archive_kofl'
  get 'archive/mexchem', :as => 'archive_mexchem'
  get 'archive/ac', :as => 'archive_ac'
  get 'archive/kimbera', :as => 'archive_kimbera'
  get 'archive/gfinburo', :as => 'archive_gfinburo'
  get 'archive/bimboa', :as => 'archive_bimboa'
  get 'archive/ienova', :as => 'archive_ienova'
  get 'archive/grumab', :as => 'archive_grumab'
  get 'archive/bsmxb', :as => 'archive_bsmxb'
  get 'archive/pinfra', :as => 'archive_pinfra'
  get 'archive/penoles', :as => 'archive_penoles'
  get 'archive/elektra', :as => 'archive_elektra'
  get 'archive/omab', :as => 'archive_omab'
  get 'archive/alsea', :as => 'archive_alsea'
  get 'archive/megacpo', :as => 'archive_megacpo'
  get 'archive/liverpolc1', :as => 'archive_liverpolc1'
  get 'archive/gcarsoa1', :as => 'archive_gcarsoa1'
  get 'archive/cuervo', :as => 'archive_cuervo'
  get 'archive/gmxt', :as => 'archive_gmxt'
  get 'archive/lalab', :as => 'archive_lalab'
  get 'archive/gentera', :as => 'archive_gentera'
  get 'archive/volara', :as => 'archive_volara'
  get 'archive/ra', :as => 'archive_ra'
  get 'archive/alpeka', :as => 'archive_alpeka'
  get 'archive/nemaka', :as => 'archive_nemaka'
  get 'archive/bbajioo', :as => 'archive_bbajioo'
  get 'archive/gcc', :as => 'archive_gcc'

  get 'podcast/index', :as => 'podcast_index'

  resources :posts

  match 'payments/cancel/view' => 'payments#cancel_view', via: :all
  match 'payments/success/view' => 'payments#success_view', via: :all
  match 'payments/webhook' => 'payments#webhook', via: :all
  get 'payment/:payment', to: "payments#show", as: :payment

  post 'payments', to: "payments#create"
  post 'conekta', to: "payments#conekta"

  get 'profile' => 'users#profile', as: :profile
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!, :user_has_any_subscription!

  def index; end

  private
end

app/views/dashboard/educacion.html.erb
<% content_for :page_title, 'Finapp - Dashboard' %>
<%= render 'shared/sidebar' %>

<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <div class="dashboard__welcome">
          <%= image_tag("sidebar-edu__icon.png", class: "dashboard__welcome-img") %>
          <span>
            Dashboard
            <h3 class="dashboard__welcome-title">Educación financiera</h3>
          </span>
        </div>
        <div class="">
          <h4 class="profile__intro-subtitle">Mini-series</h4>
          <div class="row profile__education">
            <div class="twelve columns ">
              <%= link_to(academy_analisisTecnico_path, class: "dashboard__education-featured-link") do %>
              <div class="dashboard__education-featured-card">
                <p class="dashboard__education-featured-subtitle">Miniserie</p>
                <h5 class="dashboard__education-featured-title">Análisis técnico <br> básico</h5>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="">
          <h4 class="profile__intro-subtitle">Educación financiera básica</h4>
          <div class="row profile__education">
            <div class="twelve columns ">
              <div class="education__categoryTheme-card3">
                <%= link_to(educacion_main_path, class: "education__categoryTheme-link") do %>
                  <h5 class="education__categoryTheme-card-title">Ir a categorías básicas</h5>
                  <p class="education__categoryTheme-card-type">6 categorías</p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="">
          <h4 class="profile__intro-subtitle">Análisis Fundamental</h4>
          <section class="education__cardsGrid-dashboard">
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_bancosCentrales_path) do %>
                  <%= image_tag("academy-bancos.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">¿Qué son bancos centrales?</p>
                <p class="education__categoryResult-card-description">Qué son los bancos centrales y su papel en el sistema financiero</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_acciones_path) do %>
                  <%= image_tag("academy-acciones.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">Acciones</p>
                <p class="education__categoryResult-card-description">Qué factores pueden influir en la cotización de las acciones.</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_bitcoin_path) do %>
                  <%= image_tag("academy-bitcoin.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">Bitcoin y las criptodivisas</p>
                <p class="education__categoryResult-card-description">Qué es el Bitcoin y qué influencia tiene su valor</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_materias_path) do %>
                  <%= image_tag("academy-materia.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">Materias primas</p>
                <p class="education__categoryResult-card-description">Por qué los factores fundamentales son cruciales en las materias primas</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_correlacion_path) do %>
                  <%= image_tag("academy-correlacion.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">Correlación entre mercados</p>
                <p class="education__categoryResult-card-description">Qué significa "correlación" y cómo puede influenciar tu operativa</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
            <article class="education__categoryResult-card">
              <div class="education__categoryResult-card-wrap">
                <%= link_to(academy_sentimiento_path) do %>
                  <%= image_tag("academy-sentimiento.jpg", class: "education__categoryResult-card-img") %>
                <% end %>
              </div>
              <div class="education__categoryResult-card-about">
                <p class="education__categoryResult-card-type">Artículo</p>
                <p class="education__categoryResult-card-title">Sentimiento de mercado</p>
                <p class="education__categoryResult-card-description">Por qué el sentimiento de mercado juega un papel tan importante en el trading</p>
                <p class="education__categoryResult-card-theme">#Premium</p>
              </div>
            </article>
          </section>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<% content_for :page_title, 'Finapp - Dashboard' %>
<%= render 'shared/sidebar' %>

<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <div class="dashboard__welcome">
          <%= image_tag("sidebar-dash__icon.png", class: "dashboard__welcome-img") %>
          <span>
            Dashboard
            <h3 class="dashboard__welcome-title">¡Hola, <%= current_user.name %>!</h3>
          </span>
        </div>
        <div class="profile__intro">
          <p class="profile__intro-subtitle">Señales activas</p>
          <div class="profile__intro-señales">
            <table class="profile__intro-table">
              <tbody>
                <tr>
                  <th class="profile__intro-tableTitle">Emisora</th>
                  <th class="profile__intro-tableTitle">Fecha</th>
                  <th class="profile__intro-tableTitle">Entrada</th>
                  <th class="profile__intro-tableTitle">Stop Loss</th>
                  <th class="profile__intro-tableTitle">O1</th>
                  <th class="profile__intro-tableTitle">O2</th>
                  <th class="profile__intro-tableTitle">O3</th>
                  <th class="profile__intro-tableTitle">Graph</th>
                </tr>
              </tbody>
              <tbody class="profile__intro-tableBody">
              </tbody>
            </table>
          </div>
        </div>
        <div class="profile__intro-videos-row">
          <h4 class="profile__intro-title">Comentarios de mercado</h4>
          <div class="dashboard__updates">

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  const players = Plyr.setup('.plyr__video-embed');
</script>

app/views/dashboard/info.html.erb
<% content_for :page_title, 'Finapp - Dashboard' %>
<%= render 'shared/sidebar' %>

<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <div class="dashboard__welcome">
          <%= image_tag("sidebar-info__icon.png", class: "dashboard__welcome-img") %>
          <span>
            Dashboard
            <h3 class="dashboard__welcome-title">Indice de Precios y Cotizaciones - IPC</h3>
          </span>
        </div>
        <div class="profile__intro">
          <p class="profile__intro-subtitle">Ratios fundamentales</p>
          <div class="profile__intro-señales">
            <table class="profile__intro-table">
              <tbody>
                <tr>
                  <th class="profile__intro-tableTitle" data-balloon-length="medium" data-balloon="Nombre de la Compañía cotizando en el Mercado de Valores." data-balloon-pos="up">Emisora</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="medium" data-balloon="Peso que tiene cada una de las 35 emisoras que componen el Indice de Precios y Cotizaciones (IPC) de la Bolsa Mexicana de Valores." data-balloon-pos="up">Participación</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="Razón Precio/Utilidad (P/U Ratio) Mide el precio de una acción dividido entre la utilidad por acción (últimos doce meses). Es decir, el precio que los inversionistas están dispuestos a pagar por una acción calculado como el número de veces de la utilidad neta." data-balloon-pos="up">P/U</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="Precio Valor en libros o PVC (Price to Book Value) es el ratio bursátil que mide la relación entre el precio al que cotizan las acciones con el valor de sus fondos propios, es decir, el valor contable de sus activos menos el valor contable de sus deudas." data-balloon-pos="up">P/VL</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="EV/EBITDA compara el valor de una empresa (EV - Enterprise Value), con los beneficios brutos antes de intereses, impuestos, amortizaciones y depreciaciones (EBITDA - Earnings Before Interest, Taxes, Depreciation and Amortization), para determinar si la empresa incorpora mayor o menor valor que el directamente relacionado con los recursos generados." data-balloon-pos="up">EV/EBITDA</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="La utilidad por acción es el beneficio o pérdida sobre cada acción (ordinaria o preferente) en función de las acciones ordinarias o preferentes que se encuentren en circulación." data-balloon-pos="up">UPA</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="Indice de Endeudamiento: Es difícil precisar el nivel de endeudamiento óptimo para el buen funcionamiento de una empresa, ya que varía entre los distintos sectores. Este ratio da una visión de la magnitud de la deuda de la empresa, relacionando el Pasivo con el respaldo brindado por su Patrimonio Neto." data-balloon-pos="up">DN/PN</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="Rentabilidad sobre el capital invertido: Se trata del ratio que más se utiliza como representativo de la rentabilidad económica. Comprende el retorno que es capaz de generar la compañía para sus proveedores de fondos, sean estos socios, o acreedores financieros." data-balloon-pos="up">ROIC</th>
                  <th class="profile__intro-tableTitle" data-balloon-length="large" data-balloon="El coeficiente Beta (β) es una medida de la volatilidad de un activo (una acción o un valor) relativa a la variabilidad del mercado, de modo que valores altos de Beta denotan más volatilidad y Beta 1,0 es equivalencia con el mercado." data-balloon-pos="up">BETA</th>
                </tr>
              </tbody>
              <tbody class="profile__intro-tableRatios">

              </tbody>
            </table>
          </div>
        </div>
        <div class="profile__intro">
          <p class="profile__intro-subtitle">Reportes de emisoras</p>
          <section class="profile__intro-emisoras">
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gfnorteo_path) do %>
                <%= image_tag("emisoras-logos/banorte.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_femsaubd_path) do %>
                <%= image_tag("emisoras-logos/femsa.svg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_amxl_path) do %>
                <%= image_tag("emisoras-logos/amxl-logo.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_walmex_path) do %>
                <%= image_tag("emisoras-logos/walmart.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gmexicob_path) do %>
                <%= image_tag("emisoras-logos/grupo-mexico.jpg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_cemexcpo_path) do %>
                <%= image_tag("emisoras-logos/cemex-logo.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_tlevisacpo_path) do %>
                <%= image_tag("emisoras-logos/televisa.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_alfaa_path) do %>
                <%= image_tag("emisoras-logos/alfa.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gapb_path) do %>
                <%= image_tag("emisoras-logos/gap.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_asurb_path) do %>
                <%= image_tag("emisoras-logos/asur.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_bimboa_path) do %>
                <%= image_tag("emisoras-logos/bimbo.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gfinburo_path) do %>
                <%= image_tag("emisoras-logos/gf-inbursa.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_mexchem_path) do %>
                <%= image_tag("emisoras-logos/mexichem.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_kofl_path) do %>
                <%= image_tag("emisoras-logos/coca-femsa.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_bsmxb_path) do %>
                <%= image_tag("emisoras-logos/santander.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_grumab_path) do %>
                <%= image_tag("emisoras-logos/gruma.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_ienova_path) do %>
                <%= image_tag("emisoras-logos/ienova.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_elektra_path) do %>
                <%= image_tag("emisoras-logos/gelektra.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_ac_path) do %>
                <%= image_tag("emisoras-logos/arcacont.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_kimbera_path) do %>
                <%= image_tag("emisoras-logos/kimberly-clark.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_omab_path) do %>
                <%= image_tag("emisoras-logos/oma.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_pinfra_path) do %>
                <%= image_tag("emisoras-logos/pinfra.jpg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_penoles_path) do %>
                <%= image_tag("emisoras-logos/penoles.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_alsea_path) do %>
                <%= image_tag("emisoras-logos/alsea.svg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_bbajioo_path) do %>
                <%= image_tag("emisoras-logos/bbajioo.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_megacpo_path) do %>
                <%= image_tag("emisoras-logos/megacable.jpg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_liverpolc1_path) do %>
                <%= image_tag("emisoras-logos/liverpool.jpg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gmxt_path) do %>
                <%= image_tag("emisoras-logos/grupo-mexico.jpg", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gcc_path) do %>
                <%= image_tag("emisoras-logos/gcc.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>
            <article class="profile__intro-emisoras-logo">
              <%= link_to(archive_gentera_path) do %>
                <%= image_tag("emisoras-logos/gentera.png", class: "profile__intro-emisoras-logo-img") %>
              <% end %>
            </article>



          </section>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/senales.html.erb
<% content_for :page_title, 'Finapp - Dashboard' %>
<%= render 'shared/sidebar' %>

<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <div class="dashboard__welcome">
          <%= image_tag("sidebar-sign__icon.png", class: "dashboard__welcome-img") %>
          <span>
            Dashboard
            <h3 class="dashboard__welcome-title">Señales bursátiles</h3>
          </span>
        </div>
        <div class="profile__intro">
          <p class="profile__intro-subtitle">Señales activas</p>
          <div class="profile__intro-señales">
            <table class="profile__intro-table">
              <tbody>
                <tr>
                  <th class="profile__intro-tableTitle">Emisora</th>
                  <th class="profile__intro-tableTitle">Fecha</th>
                  <th class="profile__intro-tableTitle">Entrada</th>
                  <th class="profile__intro-tableTitle">Stop Loss</th>
                  <th class="profile__intro-tableTitle">O1</th>
                  <th class="profile__intro-tableTitle">O2</th>
                  <th class="profile__intro-tableTitle">O3</th>
                  <th class="profile__intro-tableTitle">Graph</th>
                </tr>
              </tbody>
              <tbody class="profile__intro-tableBody">
              </tbody>
            </table>
          </div>
        </div>
        <h4 class="profile__intro-title">Videos y seguimiento</h4>
        <div class="dashboard__videos">

        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  const players = Plyr.setup('#player');
</script>