config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/pages/*id' => 'pages#show', as: :page, format: false

  root 'main#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  get 'main/senales', :as => 'senales_main'
  get 'main/educacion', :as => 'educacion_main'
  get 'main/plans', :as => 'plans_main'
  get 'main/premium', :as => 'premium_main'
  get 'main/welcome', :as => 'welcome_main'
  get 'main/ayuda', :as => 'ayuda_main'

  get 'dashboard/index', :as => 'dashboard_index'
  get 'dashboard/educacion', :as => 'dashboard_educacion'
  get 'dashboard/senales', :as => 'dashboard_senales'
  get 'dashboard/info', :as => 'dashboard_info'

  #Articles
  get 'academy/articulo', :as => 'academy_articulo'
  get 'academy/analisisTecnico', :as => 'academy_analisisTecnico'
  get 'academy/analisisTecnicoL1', :as => 'academy_analisisTecnicoL1'
  get 'academy/analisisTecnicoL2', :as => 'academy_analisisTecnicoL2'
  get 'academy/analisisTecnicoL3', :as => 'academy_analisisTecnicoL3'
  get 'academy/analisisTecnicoL4', :as => 'academy_analisisTecnicoL4'
  get 'academy/analisisTecnicoL5', :as => 'academy_analisisTecnicoL5'
  get 'academy/analisisTecnicoL6', :as => 'academy_analisisTecnicoL6'
  get 'academy/bancosCentrales', :as => 'academy_bancosCentrales'
  get 'academy/acciones', :as => 'academy_acciones'
  get 'academy/bitcoin', :as => 'academy_bitcoin'
  get 'academy/materias', :as => 'academy_materias'
  get 'academy/correlacion', :as => 'academy_correlacion'
  get 'academy/sentimiento', :as => 'academy_sentimiento'

  #Archive
  get 'archive/amxl', :as => 'archive_amxl'
  get 'archive/femsaubd', :as => 'archive_femsaubd'
  get 'archive/gfnorteo', :as => 'archive_gfnorteo'
  get 'archive/walmex', :as => 'archive_walmex'
  get 'archive/gmexicob', :as => 'archive_gmexicob'
  get 'archive/cemexcpo', :as => 'archive_cemexcpo'
  get 'archive/tlevisacpo', :as => 'archive_tlevisacpo'
  get 'archive/alfaa', :as => 'archive_alfaa'
  get 'archive/gapb', :as => 'archive_gapb'
  get 'archive/asurb', :as => 'archive_asurb'
  get 'archive/kofl', :as => 'archive_kofl'
  get 'archive/mexchem', :as => 'archive_mexchem'
  get 'archive/ac', :as => 'archive_ac'
  get 'archive/kimbera', :as => 'archive_kimbera'
  get 'archive/gfinburo', :as => 'archive_gfinburo'
  get 'archive/bimboa', :as => 'archive_bimboa'
  get 'archive/ienova', :as => 'archive_ienova'
  get 'archive/grumab', :as => 'archive_grumab'
  get 'archive/bsmxb', :as => 'archive_bsmxb'
  get 'archive/pinfra', :as => 'archive_pinfra'
  get 'archive/penoles', :as => 'archive_penoles'
  get 'archive/elektra', :as => 'archive_elektra'
  get 'archive/omab', :as => 'archive_omab'
  get 'archive/alsea', :as => 'archive_alsea'
  get 'archive/megacpo', :as => 'archive_megacpo'
  get 'archive/liverpolc1', :as => 'archive_liverpolc1'
  get 'archive/gcarsoa1', :as => 'archive_gcarsoa1'
  get 'archive/cuervo', :as => 'archive_cuervo'
  get 'archive/gmxt', :as => 'archive_gmxt'
  get 'archive/lalab', :as => 'archive_lalab'
  get 'archive/gentera', :as => 'archive_gentera'
  get 'archive/volara', :as => 'archive_volara'
  get 'archive/ra', :as => 'archive_ra'
  get 'archive/alpeka', :as => 'archive_alpeka'
  get 'archive/nemaka', :as => 'archive_nemaka'
  get 'archive/bbajioo', :as => 'archive_bbajioo'
  get 'archive/gcc', :as => 'archive_gcc'

  get 'podcast/index', :as => 'podcast_index'

  resources :posts

  match 'payments/cancel/view' => 'payments#cancel_view', via: :all
  match 'payments/success/view' => 'payments#success_view', via: :all
  match 'payments/webhook' => 'payments#webhook', via: :all
  get 'payment/:payment', to: "payments#show", as: :payment

  post 'payments', to: "payments#create"
  post 'conekta', to: "payments#conekta"

  get 'profile' => 'users#profile', as: :profile
end

app/views/shared/_conekta_form.html.erb
<%= form_tag payments_path, method: :post, id: "card-form" do %>
<div class="conekta-paymentForm conekta-paymentForm__divider">
  <h4 class="conekta-paymentForm__title">Pago con tarjeta de crédito/débito</h4>
  <select name="plan[name]" class="paypal__select conekta-paymentForm__select">
    <option value="Monthly">Mensual : $750.00 MXN</option>
    <option value="Yearly">Anual : $8,250.00 MXN</option>
  </select>
  <input type="hidden" value="conekta" name="source" />
  <span class="card-errors"></span>
  <div>
    <label>
      <span>Nombre completo</span>
      <input class="conekta-paymentForm__input" type="text" size="20" data-conekta="card[name]">
    </label>
  </div>
  <div>
    <label>
      <span>Numero de tarjeta <%= image_tag("cards-ck.svg", class: "conekta-paymentForm__icon") %> </span>
      <input class="conekta-paymentForm__input" type="text" size="20" data-conekta="card[number]">
    </label>
  </div>
  <div>
    <label>
      <span class="display-block">Fecha exp. (MM/YYYY)</span>
      <input class="conekta-paymentForm__input small-input" type="text" size="2" data-conekta="card[exp_month]">
      <input class="conekta-paymentForm__input small-input" type="text" size="4" data-conekta="card[exp_year]">
    </label>
  </div>
  <div>
    <label>
      <span class="display-block">CVC</span>
      <input class="conekta-paymentForm__input small-input" type="text" size="4" data-conekta="card[cvc]">
    </label>
  </div>
  <div>
    <label>
      <div class="display-inline">
        <span class="display-block">Teléfono</span>
        <input class="conekta-paymentForm__input medium-input" type="text" name="payment[telephone]" required>
      </div>
      <div class="display-inline">
        <span class="display-block">Cupón</span>
        <input class="conekta-paymentForm__input medium-input" type="text" name="coupon[code]" />
      </div>
    </label>
  </div>
  <button type="submit" class="button-min">Subscribirme</button>
</div>
<% end %>

<script>
 $(function () {
   Conekta.setPublicKey('<%= ENV['CONEKTA_PUBLIC_KEY'] %>');

   var conektaSuccessResponseHandler = function(token) {
     var $form = $("#card-form");
     $form.append($('<input type="hidden" name="payment[token]" id="conektaTokenId" />').val(token.id));
     console.log($form);
     $form.get(0).submit();
   };
   var conektaErrorResponseHandler = function(response) {
     var $form = $("#card-form");
     $form.find(".card-errors").text(response.message_to_purchaser);
     $form.find("button").prop("disabled", false);
   };

   $("#card-form").submit(function(event) {
     var $form = $(this);
     $form.find("button").prop("disabled", true);
     Conekta.Token.create($form, conektaSuccessResponseHandler, conektaErrorResponseHandler);
     return false;
   });
 });
</script>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
     <div>
          <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
          <ul>
               <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
               <% end %>
          </ul>
     </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="six columns">
        <%= link_to(root_path) do %>
          <%= image_tag("logo-blue.svg", class: "footer__logo", :id => "navbarImage") %>
        <% end %>
        <p class="footer__text">© 2018 VanfinApp Tech</p>
        <p class="footer__text">Todos los derechos reservados.</p>
        <p class="footer__text">Creado por <a class="footer__link" href="http://www.vanfintec.com">Vanfintec</a>.</p>
        <div class="footer__social">
          <a href="https://www.facebook.com/culturafinapp/" target="_blank"><i class="fab fa-facebook footer__icon"></i></a>
          <a href="https://www.twitter.com/culturafinapp/" target="_blank"><i class="fab fa-twitter footer__icon"></i></a>
          <a href="https://www.instagram.com/culturafinapp/" target="_blank"><i class="fab fa-instagram footer__icon"></i></a>
          <a href="#"><i class="fab fa-linkedin footer__icon"></i></a>
        </div>
      </div>
      <div class="three columns">
        <p class="footer__title">Acerca de</p>
        <%= link_to "Educacion financiera", educacion_main_path, class: "footer__text" %>
        <%= link_to "Señales de inversión", senales_main_path, class: "footer__text" %>
        <%= link_to "Acerca de", root_path, class: "footer__text" %>
      </div>
      <div class="three columns">
        <p class="footer__title">Más información</p>
        <p class="footer__text">Términos y condiciones</p>
        <p class="footer__text">Aviso de privacidad</p>
        <%= link_to "Centro de ayuda", ayuda_main_path, class: "footer__text" %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav-alt.html.erb
<nav class="navbar navbar-edu">
  <div class="navbar__container">
    <div class="navbar__logo">
      <%= link_to(root_path) do %>
        <%= image_tag("logo-blue.svg", class: "navbar__logo-img") %>
      <% end %>
    </div>
    <div class="navbar-sign__menu">
      <%= link_to "Educacion", educacion_main_path, class: "navbar-sign__menu-link" %>
      <% if user_signed_in? %>
        <% if current_user.account? && current_user.account.any_subscription? %>
          <%= link_to "Dashboard", dashboard_index_path, class: "navbar-sign__menu-link" %>
          <% else %>
          <%= link_to "Señales", senales_main_path, class: "navbar-sign__menu-link" %>
          <%= link_to "Perfil", profile_path, class: "navbar-sign__menu-link" %>
          <%= link_to "¡Únete a Premium!", premium_main_path, class: "navbar-sign__menu-link button-premiumNav" %>
        <% end %>
      <% else %>
      <%= link_to "Señales", senales_main_path, class: "navbar-sign__menu-link" %>
      <%= link_to "Crear cuenta", new_user_registration_path, class: "navbar-sign__menu-link button-min-alpha" %>
      <%= link_to "Inicia sesión", new_user_session_path, class: "navbar-sign__menu-link button-min-white"  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_nav.html.erb
<nav class="navbar">
  <div class="navbar__container">
    <div class="navbar__logo">
      <%= link_to(root_path) do %>
        <%= image_tag("logo-blue.svg", class: "navbar__logo-img") %>
      <% end %>
    </div>
    <div class="navbar__menu">
      <%= link_to "Educacion", educacion_main_path, class: "navbar__menu-link" %>
      <% if user_signed_in? %>
        <% if current_user.account? && current_user.account.any_subscription? %>
          <%= link_to "Dashboard", dashboard_index_path, class: "navbar__menu-link" %>
          <% else %>
          <%= link_to "Señales", senales_main_path, class: "navbar__menu-link" %>
          <%= link_to "Perfil", profile_path, class: "navbar__menu-link" %>
          <%= link_to "¡Únete a Premium!", premium_main_path, class: "navbar__menu-link button-premiumNav" %>
        <% end %>
      <% else %>
      <%= link_to "Señales", senales_main_path, class: "navbar__menu-link" %>
      <%= link_to "Crear cuenta", new_user_registration_path, class: "navbar-sign__menu-link button-min-alphaBlue" %>
      <%= link_to "Inicia sesión", new_user_session_path, class: "navbar-sign__menu-link button-min"  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_paypal_form.html.erb
<div class="conekta-paymentForm">
  <form action='<%= PaypalServiceBase::form_url %>' method="post" target="_top">
    <h4 class="conekta-paymentForm__title">Pago con Paypal</h4>
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="<%= PaypalServiceBase::HOSTED_BUTTON_ID %>">
    <input type="hidden" name="on0" value="">
    <select name="os0" class="paypal__select conekta-paymentForm__select display-block">
      <option value="Mensual">Mensual : $750.00 MXN</option>
      <option value="Anual">Anual : $8,250.00 MXN</option>
    </select>
    <div>
      <label>
        <span>Cupón</span>
        <input class="conekta-paymentForm__input" type="text" name="coupon[code]" />
      </label>
    </div>
    <input type="hidden" name="currency_code" value="<%= PaypalServiceBase::CURRENCY_CODE %>">
    <input type="hidden" name="custom" value="<%=user.id%>">
    <input type="submit" value="Subscribirme" name="submit" title="PayPal - The safer, easier way to pay online!" class="button-paypal">
    <%= image_tag("paypal-logo.png", class: "paypal-logo") %>
    <img alt="" border="0" src="https://www.paypal.com/es_XC/i/scr/pixel.gif" width="1" height="1">
  </form>

</div>

app/views/shared/_responsive-nav.html.erb
<div id='cssmenu'>
  <ul class="std-text">
    <li><%= link_to "Inicio", root_path, class: "navbar__menu-link" %></li>
    <li><%= link_to "Educacion", educacion_main_path, class: "navbar__menu-link" %></li>
    <li><%= link_to "Señales", senales_main_path, class: "navbar__menu-link" %></li>
    <% if user_signed_in? %>
    <% if current_user.account? && current_user.account.any_subscription? %>
      <li><%= link_to "Dashboard", dashboard_index_path, class: "navbar__menu-link" %></li>
      <% else %>
      <li><%= link_to "Perfil", profile_path, class: "navbar__menu-link" %></li>
    <% end %>
      <li><%= link_to "Cerrar sesión", destroy_user_session_path, class: "navbar__menu-link" %></li>
    <% else %>
      <li><%= link_to "Inicia sesión", new_user_session_path, class: "navbar__menu-link"  %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_sidebar.html.erb
<div class="s-layout__sidebar">
  <div class="s-sidebar__trigger" id="sidebar__trigger">
     <i class="fa fa-bars"></i>
     <%= image_tag("logo-icon-white.svg", class: "sidebar__logo-icon", :id => "navbarImage") %>
  </div>

  <nav class="s-sidebar__nav" id="sidebar__nav">

    <div class="sidebar__logo">
      <%= link_to(root_path) do %>
        <%= image_tag("logo-white.svg", class: "navbar__logo-img", :id => "navbarImage") %>
      <% end %>
    </div>

     <ul>
       <% if current_user.account? && current_user.account.any_subscription? %>
         <li>
           <%= link_to(dashboard_index_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
             <i><%= image_tag("sidebar-dash__icon.png", class: "sidebar__menu-img") %></i>
             <span>Dashboard</span>
           <% end %>
         </li>
         <li>
           <%= link_to(dashboard_educacion_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
              <i><%= image_tag("sidebar-edu__icon.png", class: "sidebar__menu-img") %></i>
              <span>Educación</span>
           <% end %>
         </li>
         <li>
           <%= link_to(dashboard_senales_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
             <i><%= image_tag("sidebar-sign__icon.png", class: "sidebar__menu-img") %></i>
             <span>Seguimiento de señales</span>
           <% end %>
         </li>
         <li>
           <%= link_to(dashboard_info_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
             <i><%= image_tag("sidebar-info__icon.png", class: "sidebar__menu-img") %></i>
             <span>Info. Fundamental</span>
           <% end %>
         </li>
       <% end %>
       <li>
         <%= link_to(profile_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
           <i><%= image_tag("sidebar-profile__icon.png", class: "sidebar__menu-img") %></i>
           <span>Mi perfil</span>
         <% end %>
       </li>
       <li>
         <%= link_to(destroy_user_session_path, class: "sidebar__menu-listItem s-sidebar__nav-link") do %>
           <i><%= image_tag("sidebar-logout__icon.png", class: "sidebar__menu-img") %></i>
           <span>Cerrar sesión</span>
         <% end %>
       </li>
     </ul>
  </nav>
</div>

<script type="text/javascript">
$( "div.s-sidebar__trigger" ).click(function() {
  $("#sidebar__nav").toggleClass( "sidebar__nav-extended" );
  $("#sidebar__trigger").toggleClass( "sidebar__trigger-extended" );
});
</script>