config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/pages/*id' => 'pages#show', as: :page, format: false

  root 'main#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  get 'main/senales', :as => 'senales_main'
  get 'main/educacion', :as => 'educacion_main'
  get 'main/plans', :as => 'plans_main'
  get 'main/premium', :as => 'premium_main'
  get 'main/welcome', :as => 'welcome_main'
  get 'main/ayuda', :as => 'ayuda_main'

  get 'dashboard/index', :as => 'dashboard_index'
  get 'dashboard/educacion', :as => 'dashboard_educacion'
  get 'dashboard/senales', :as => 'dashboard_senales'
  get 'dashboard/info', :as => 'dashboard_info'

  #Articles
  get 'academy/articulo', :as => 'academy_articulo'
  get 'academy/analisisTecnico', :as => 'academy_analisisTecnico'
  get 'academy/analisisTecnicoL1', :as => 'academy_analisisTecnicoL1'
  get 'academy/analisisTecnicoL2', :as => 'academy_analisisTecnicoL2'
  get 'academy/analisisTecnicoL3', :as => 'academy_analisisTecnicoL3'
  get 'academy/analisisTecnicoL4', :as => 'academy_analisisTecnicoL4'
  get 'academy/analisisTecnicoL5', :as => 'academy_analisisTecnicoL5'
  get 'academy/analisisTecnicoL6', :as => 'academy_analisisTecnicoL6'
  get 'academy/bancosCentrales', :as => 'academy_bancosCentrales'
  get 'academy/acciones', :as => 'academy_acciones'
  get 'academy/bitcoin', :as => 'academy_bitcoin'
  get 'academy/materias', :as => 'academy_materias'
  get 'academy/correlacion', :as => 'academy_correlacion'
  get 'academy/sentimiento', :as => 'academy_sentimiento'

  #Archive
  get 'archive/amxl', :as => 'archive_amxl'
  get 'archive/femsaubd', :as => 'archive_femsaubd'
  get 'archive/gfnorteo', :as => 'archive_gfnorteo'
  get 'archive/walmex', :as => 'archive_walmex'
  get 'archive/gmexicob', :as => 'archive_gmexicob'
  get 'archive/cemexcpo', :as => 'archive_cemexcpo'
  get 'archive/tlevisacpo', :as => 'archive_tlevisacpo'
  get 'archive/alfaa', :as => 'archive_alfaa'
  get 'archive/gapb', :as => 'archive_gapb'
  get 'archive/asurb', :as => 'archive_asurb'
  get 'archive/kofl', :as => 'archive_kofl'
  get 'archive/mexchem', :as => 'archive_mexchem'
  get 'archive/ac', :as => 'archive_ac'
  get 'archive/kimbera', :as => 'archive_kimbera'
  get 'archive/gfinburo', :as => 'archive_gfinburo'
  get 'archive/bimboa', :as => 'archive_bimboa'
  get 'archive/ienova', :as => 'archive_ienova'
  get 'archive/grumab', :as => 'archive_grumab'
  get 'archive/bsmxb', :as => 'archive_bsmxb'
  get 'archive/pinfra', :as => 'archive_pinfra'
  get 'archive/penoles', :as => 'archive_penoles'
  get 'archive/elektra', :as => 'archive_elektra'
  get 'archive/omab', :as => 'archive_omab'
  get 'archive/alsea', :as => 'archive_alsea'
  get 'archive/megacpo', :as => 'archive_megacpo'
  get 'archive/liverpolc1', :as => 'archive_liverpolc1'
  get 'archive/gcarsoa1', :as => 'archive_gcarsoa1'
  get 'archive/cuervo', :as => 'archive_cuervo'
  get 'archive/gmxt', :as => 'archive_gmxt'
  get 'archive/lalab', :as => 'archive_lalab'
  get 'archive/gentera', :as => 'archive_gentera'
  get 'archive/volara', :as => 'archive_volara'
  get 'archive/ra', :as => 'archive_ra'
  get 'archive/alpeka', :as => 'archive_alpeka'
  get 'archive/nemaka', :as => 'archive_nemaka'
  get 'archive/bbajioo', :as => 'archive_bbajioo'
  get 'archive/gcc', :as => 'archive_gcc'

  get 'podcast/index', :as => 'podcast_index'

  resources :posts

  match 'payments/cancel/view' => 'payments#cancel_view', via: :all
  match 'payments/success/view' => 'payments#success_view', via: :all
  match 'payments/webhook' => 'payments#webhook', via: :all
  get 'payment/:payment', to: "payments#show", as: :payment

  post 'payments', to: "payments#create"
  post 'conekta', to: "payments#conekta"

  get 'profile' => 'users#profile', as: :profile
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  validates :title, :content, :category_id, presence: true
  default_scope { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = post_scope
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'The post was created!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Update successful'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post destroyed'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def params_category_conditions
    params.slice(:category_name)
          .transform_keys { |key| key.gsub 'category_', '' }
          .permit.to_h
  end

  def post_scope
    %i[by_category].reduce(Post.all) do |scope, reducer|
      send "scope_#{reducer}".to_sym, scope
    end
  end

  def scope_by_category(scope)
    return scope unless params_category_conditions.any?

    scope.joins(:category).merge Category.where params_category_conditions
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

    <%= render 'shared/error_messages' %>

     <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category" }) %><br>
     <%= f.label :title %><br>
     <%= f.text_field :title, placeholder: "Type the post title here" %><br>
     <%= f.label :content %><br>
     <%= f.text_area :content, size: "60x12", placeholder: "Type the post tect here" %><br>

     <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<%= render 'shared/nav-alt' %>

<div class="education__header">
  <div class="row">
    <div class="six columns">
      <div class="education__header-categories">
        <img class="education__header-cover" src="../assets/images/edu__cover.png" alt="">
      </div>
    </div>
    <div class="six columns">
      <div class="education__header-bg">
        <h2 class="education__header-title">Iniciando tu camino a una mejor cultura financiera,
          con información sencilla que te sorprenderá.</h2>
        <p class="education__header-subtitle">Suscibete a nuestro newsletter y recibe las lecciones más valiosas</p>
        <form class="" action="index.html" method="post">
          <input class="education__header-search" type="email" name="search" placeholder="bernardo@vanfinapp.com">
          <a class="education__header-button button-min" href="../login.html">Suscribir</a>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="education__top">
  <div class="container">
    <div class="row">
      <div class="offset-by-three six columns ">
        <h2 class="education__top-title">El conocimiento lleva a buenas decisiones</h2>
      </div>
    </div>
    <div class="row">
      <div class="offset-by-three six columns ">
        <p class="education__top-text">Por medio de cápsulas, folletos, calculadoras y demás herramientas que busquen que el usuario pueda tomar buenas decisiones financieras, tomar el control de su capital y utilizar los diferentes instrumentos que hay en el mercado para ahorrar e invertir.</p>
      </div>
    </div>
  </div>
</div>

<div class="education__top">
  <div class="container">
    <div class="row">
      <div class="offset-by-three six columns ">
        <h2 class="education__top-title">Lecciones por tema</h2>
      </div>
    </div>

    <div class="row">
      <div class="four columns ">
        <div class="education__categoryTheme-card">
          <a href="../educacion/categoria.html">
            <div class="education__categoryTheme-card-wrap">
              <img class="education__categoryTheme-card-icon" src="../assets/images/edu-tema_tarjeta.svg" alt="">
            </div>
            <div class="education__categoryTheme-card-about">
              <h5 class="education__categoryTheme-card-title">Tarjetas</h5>
              <p class="education__categoryTheme-card-description">Aprende todo lo necesario para sacarle el mayor provecho a tu tarjeta, o elegir la correcta para tí.</p>
              <p class="education__categoryTheme-card-type">5 lecciones</p>
            </div>
          </a>
        </div>
      </div>
      <div class="four columns ">
        <div class="education__categoryTheme-card">
          <a href="../educacion/categoria.html">
            <div class="education__categoryTheme-card-wrap">
              <img class="education__categoryTheme-card-icon" src="../assets/images/edu-tema_credito.svg" alt="">
            </div>
            <div class="education__categoryTheme-card-about">
              <h5 class="education__categoryTheme-card-title">Créditos</h5>
              <p class="education__categoryTheme-card-description">Ya sean hipotecários o de automóvil, encuentra todo lo que necesites saber para tu próximo crédito.</p>
              <p class="education__categoryTheme-card-type">8 lecciones</p>
            </div>
          </a>
        </div>
      </div>
      <div class="four columns ">
        <div class="education__categoryTheme-card">
          <a href="../educacion/categoria.html">
            <div class="education__categoryTheme-card-wrap">
              <img class="education__categoryTheme-card-icon" src="../assets/images/edu-tema_admin.svg" alt="">
            </div>
            <div class="education__categoryTheme-card-about">
              <h5 class="education__categoryTheme-card-title">Admin Personal</h5>
              <p class="education__categoryTheme-card-description">Aprende todo lo necesario para sacarle el mayor provecho a tu tarjeta, o elegir la correcta para tí.</p>
              <p class="education__categoryTheme-card-type">3 lecciones</p>
            </div>
          </a>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="education__intro">
  <div class="container">
    <div class="row">
      <div class="twelve columns ">
        <h2 class="education__intro-title">Lo más nuevo</h2>
      </div>
    </div>
    <div class="row ">
      <div class="offset-by-two four columns">
        <h3 class="education__intro-subtitle">"Quiero empezar a ahorrar"</h3>
        <p class="education__intro-about">Ahorrar es una acción muy importante para todas las personas que reciben un ingreso. No siempre es necesario gastarse todo lo que recibimos, ya que más adelante nos puede servir. Aca te decimos como encontrar la mejor manera para ti.</p>
      </div>
      <div class="four columns">
        <div class="education__categoryResult-card">
          <a href="../educacion/video.html">
            <div class="education__categoryResult-card-wrap">
              <img class="education__categoryResult-card-img" src="../assets/images/credit-cover-3.png" alt="">
            </div>
            <div class="education__categoryResult-card-about">
              <p class="education__categoryResult-card-type">Video</p>
              <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
              <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
              <p class="education__categoryResult-card-theme">#Créditos</p>
            </div>
          </a>
        </div>
      </div>
    </div>

    <div class="row ">
      <div class="four columns">
        <div class="education__categoryResult-card">
          <a href="../educacion/video.html">
            <div class="education__categoryResult-card-wrap">
              <img class="education__categoryResult-card-img" src="../assets/images/credit-cover-3.png" alt="">
            </div>
            <div class="education__categoryResult-card-about">
              <p class="education__categoryResult-card-type">Video</p>
              <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
              <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
              <p class="education__categoryResult-card-theme">#Créditos</p>
            </div>
          </a>
        </div>
      </div>
      <div class="four columns">
        <div class="education__categoryResult-card">
          <a href="../educacion/articulo.html">
            <div class="education__categoryResult-card-wrap">
              <img class="education__categoryResult-card-img" src="../assets/images/articulo-cover.jpg" alt="">
            </div>
            <div class="education__categoryResult-card-about">
              <p class="education__categoryResult-card-type">Artículo</p>
              <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
              <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
              <p class="education__categoryResult-card-theme">#Créditos</p>
            </div>
          </a>
        </div>
      </div>
      <div class="four columns">
        <div class="education__categoryResult-card">
          <a href="../educacion/video.html">
            <div class="education__categoryResult-card-wrap">
              <img class="education__categoryResult-card-img" src="../assets/images/credit-cover-2.png" alt="">
            </div>
            <div class="education__categoryResult-card-about">
              <p class="education__categoryResult-card-type">Video</p>
              <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
              <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
              <p class="education__categoryResult-card-theme">#Créditos</p>
            </div>
          </a>
        </div>
      </div>
    </div>

    <div class="row ">
      <div class="four columns">
        <div class="education__categoryResult-card">
          <div class="education__categoryResult-card-wrap">
            <img class="education__categoryResult-card-img" src="../assets/images/credit-cover-3.png" alt="">
          </div>
          <div class="education__categoryResult-card-about">
            <p class="education__categoryResult-card-type">Video</p>
            <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
            <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
            <p class="education__categoryResult-card-theme">#Créditos</p>
          </div>
        </div>
      </div>
      <div class="four columns">
        <div class="education__categoryResult-card">
          <div class="education__categoryResult-card-wrap">
            <img class="education__categoryResult-card-img" src="../assets/images/credit-cover.png" alt="">
          </div>
          <div class="education__categoryResult-card-about">
            <p class="education__categoryResult-card-type">Artículo</p>
            <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
            <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
            <p class="education__categoryResult-card-theme">#Créditos</p>
          </div>
        </div>
      </div>
      <div class="four columns">
        <div class="education__categoryResult-card">
          <div class="education__categoryResult-card-wrap">
            <img class="education__categoryResult-card-img" src="../assets/images/credit-cover-2.png" alt="">
          </div>
          <div class="education__categoryResult-card-about">
            <p class="education__categoryResult-card-type">Video</p>
            <p class="education__categoryResult-card-title">“Necesito un préstamo”</p>
            <p class="education__categoryResult-card-description">Si tienes la necesidad de un prestamo hay varias cosas que tienes que saber antes de hacerlo, aqui te las explicamos de la mejor manera.</p>
            <p class="education__categoryResult-card-theme">#Créditos</p>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="education__outro">
  <div class="container">
    <div class="row ">
      <div class="twelve columns">
        <h2 class="landing__outro-title">Lleva tu cultura financiera al siguiente nivel</h2>
        <h5 class="landing__outro-quote">¿En qué tema podemos apoyarte?</h5>
        <div class="education__header-categories-blockC">
          <a class="education__header-categories-link" href="#">
            <div class="">
              <img class="education__header-categories-icon" src="../assets/images/edu-tema_tarjeta.svg" alt="">
              <p class="education__header-categories-sub">Tarjetas</p>
            </div>
          </a>
        </div>
        <div class="education__header-categories-blockC">
          <a class="education__header-categories-link" href="#">
            <div class="">
              <img class="education__header-categories-icon" src="../assets/images/edu-tema_credito.svg" alt="">
              <p class="education__header-categories-sub">Créditos</p>
            </div>
          </a>
        </div>
        <div class="education__header-categories-blockC">
          <a class="education__header-categories-link" href="#">
            <div class="">
              <img class="education__header-categories-icon" src="../assets/images/edu-tema_admin.svg" alt="">
              <p class="education__header-categories-sub">Ahorro</p>
            </div>
          </a>
        </div>

      </div>
    </div>
    <div class="education__suggest">
      <div class="row">
        <div class="six columns ">
          <h2 class="education__suggest-title">¿Te quedaron preguntas?</h2>
          <p class="education__suggest-text">Si aun tienes dudas, o quisieras saber más sobre ciertos temas, dejanos tu correo y cuentanos sobre que te interesa aprender o que temas te gustan más y tomaremos tu opinion en cuenta, ya que todos los días estamos trabajando en contenido de interés.</p>
        </div>
        <div class="six columns ">
          <input class="education__suggest-mail" type="email" name="mail" placeholder="bernardo@finapp.com"> <br>
          <input class="education__suggest-theme" type="text" name="search" placeholder="Me gustaría ver más sobre..."> <br>
          <a class="button-min" href="/login.html">Enviar</a>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.sr = ScrollReveal();
  sr.reveal(".");
</script>

<h1>Listing Posts</h1>

<% @posts.each do |post| %>
     <h1><%= post.title %></h1>
     <p><%= post.content %></p>
     <%= link_to 'Show', post %>
     <%= link_to 'Edit', edit_post_path(post) %>
     <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" } %>